

    CREATE SCHEMA `logdb` DEFAULT CHARACTER SET utf8  COLLATE utf8_general_ci;
    
    GRANT ALL PRIVILEGES ON `logdb`.* TO 'serverConnect'@'%';
    
    USE `logdb`;
    
    CREATE TEMPORARY TABLE log (  
        `index` bigint(20) NOT NULL AUTO_INCREMENT,
        `Account` varchar(128) NOT NULL,
        `PlayerID` bigint(20) NOT NULL,
        `Time` bigint(20) NOT NULL,
        `ActivityEvent` int(11) NOT NULL,
        `IValue1` bigint(20) NOT NULL DEFAULT '0',
        `IValue2` bigint(20) NOT NULL DEFAULT '0',
        `IValue3` bigint(20) NOT NULL DEFAULT '0',
        `SValue1` varchar(128) NOT NULL DEFAULT '',
        `SValue2` varchar(128) NOT NULL DEFAULT '',
        `SValue3` varchar(128) NOT NULL DEFAULT '',
        `Msg` text NOT NULL,
        PRIMARY KEY (`index`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
    
    CREATE TABLE IF NOT EXISTS `20200701` LIKE log;
CREATE TABLE IF NOT EXISTS `20200702` LIKE log;
CREATE TABLE IF NOT EXISTS `20200703` LIKE log;
CREATE TABLE IF NOT EXISTS `20200704` LIKE log;
CREATE TABLE IF NOT EXISTS `20200705` LIKE log;
CREATE TABLE IF NOT EXISTS `20200706` LIKE log;
CREATE TABLE IF NOT EXISTS `20200707` LIKE log;
CREATE TABLE IF NOT EXISTS `20200708` LIKE log;
CREATE TABLE IF NOT EXISTS `20200709` LIKE log;
CREATE TABLE IF NOT EXISTS `20200710` LIKE log;
CREATE TABLE IF NOT EXISTS `20200711` LIKE log;
CREATE TABLE IF NOT EXISTS `20200712` LIKE log;
CREATE TABLE IF NOT EXISTS `20200713` LIKE log;
CREATE TABLE IF NOT EXISTS `20200714` LIKE log;
CREATE TABLE IF NOT EXISTS `20200715` LIKE log;
CREATE TABLE IF NOT EXISTS `20200716` LIKE log;
CREATE TABLE IF NOT EXISTS `20200717` LIKE log;
CREATE TABLE IF NOT EXISTS `20200718` LIKE log;
CREATE TABLE IF NOT EXISTS `20200719` LIKE log;
CREATE TABLE IF NOT EXISTS `20200720` LIKE log;
CREATE TABLE IF NOT EXISTS `20200721` LIKE log;
CREATE TABLE IF NOT EXISTS `20200722` LIKE log;
CREATE TABLE IF NOT EXISTS `20200723` LIKE log;
CREATE TABLE IF NOT EXISTS `20200724` LIKE log;
CREATE TABLE IF NOT EXISTS `20200725` LIKE log;
CREATE TABLE IF NOT EXISTS `20200726` LIKE log;
CREATE TABLE IF NOT EXISTS `20200727` LIKE log;
CREATE TABLE IF NOT EXISTS `20200728` LIKE log;
CREATE TABLE IF NOT EXISTS `20200729` LIKE log;
CREATE TABLE IF NOT EXISTS `20200730` LIKE log;
    

    CREATE SCHEMA `gamedb` DEFAULT CHARACTER SET utf8  COLLATE utf8_general_ci;
    
    GRANT ALL PRIVILEGES ON `gamedb`.* TO 'serverConnect'@'%';
    
    USE `gamedb`;
    
    CREATE TABLE IF NOT EXISTS `attach` (
      `PlayerID` bigint NOT NULL,
      `PlayerIDStr` varchar(128) NOT NULL,
      `Kind` bigint NOT NULL,
      `Type` bigint NOT NULL,
      `IValue` bigint NOT NULL,
      PRIMARY KEY (`PlayerID`,`Kind`,`Type`,`PlayerIDStr`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
    
    CREATE TABLE IF NOT EXISTS `setting` (
      `Key` varchar(40) NOT NULL,
      `IValue` int DEFAULT '0',
      `SValue` varchar(60) DEFAULT '',
      PRIMARY KEY (`Key`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
    

